import {
  Rocket,
  LayoutDashboard,
  Hammer,
  Cpu,
  Globe,
  Settings,
  FolderOpen,
  Mail,
  Database,
  Monitor,
  Server,
  Building,
  Send,
  Shield,
  Code,
  User,
  CreditCard,
  Users,
  Zap,
  Cylinder,
  Info
} from 'lucide-react';

export const HELP_CATEGORIES = [
  { id: 'getting-started', title: 'Primeiros Passos', description: 'Tudo o que precisas de saber antes de criar o teu site', icon: Rocket, count: 40 },
  { id: 'hpanel', title: 'hPanel', description: 'As funcionalidades do painel de controlo', icon: LayoutDashboard, count: 58 },
  { id: 'website-builder', title: 'Construtor de Sites', description: 'Tudo o que precisas de saber sobre o construtor de sites', icon: Hammer, count: 269 },
  { id: 'horizons', title: 'Horizons', description: 'Tudo sobre o Horizons - a nossa ferramenta baseada em IA', icon: Cpu, count: 65 },
  { id: 'domains', title: 'Domínios', description: 'Informações úteis sobre compra, transferência e gestão de domínios', icon: Globe, count: 86 },
  { id: 'dns', title: 'DNS', description: 'Como gerir a Zona DNS do teu domínio', icon: Settings, count: 79 },
  { id: 'files', title: 'Gestão de Ficheiros', description: 'Acesso a ficheiros, backups, FTP, SFTP e SSH', icon: FolderOpen, count: 55 },
  { id: 'email', title: 'E-mail', description: 'Como configurar e gerir as tuas contas de e-mail', icon: Mail, count: 127 },
  { id: 'mysql', title: 'Bases de Dados MySQL', description: 'Informação sobre gestão de bases de dados', icon: Database, count: 24 },
  { id: 'website', title: 'Website', description: 'Desenvolvimento de sites, desde os primeiros passos ao SEO', icon: Monitor, count: 105 },
  { id: 'vps', title: 'VPS', description: 'Base de Conhecimento de Servidores Virtuais Privados (VPS)', icon: Server, count: 272 },
  { id: 'agency', title: 'Planos de Agência', description: 'Informação sobre planos de alojamento para agências', icon: Building, count: 26 },
  { id: 'reach', title: 'Reach', description: 'Ferramenta de e-mail marketing simples e baseada em IA', icon: Send, count: 50 },
  { id: 'ssl', title: 'Certificados SSL', description: 'Tudo o que precisas de saber sobre certificados SSL', icon: Shield, count: 19 },
  { id: 'php', title: 'PHP', description: 'Alterações na configuração PHP da tua conta', icon: Code, count: 20 },
  { id: 'profile', title: 'Gestão de Perfil', description: 'Toda a informação sobre a gestão da tua conta', icon: User, count: 24 },
  { id: 'billing', title: 'Faturação', description: 'Informação sobre faturas, pagamentos e subscrições', icon: CreditCard, count: 39 },
  { id: 'affiliates', title: 'Afiliados e Referências', description: 'Informação sobre os programas de afiliados e referências', icon: Users, count: 13 },
  { id: 'features', title: 'Funcionalidades', description: 'Informação sobre diferentes ferramentas e tecnologias', icon: Zap, count: 37 },
  { id: 'cpanel', title: 'cPanel', description: 'Gestão dos teus serviços através do cPanel', icon: Cylinder, count: 67 },
  { id: 'about', title: 'Sobre Nós', description: 'Informação sobre a nossa empresa', icon: Info, count: 13 },
];
